"""add collection and collection_item models

Revision ID: 0bf9abf0e21e
Revises: a11a5f31265f
Create Date: 2026-07-03 14:47:04.125137

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bf9abf0e21e"
down_revision: Union[str, Sequence[str], None] = "a11a5f31265f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "cover_image_url",
            sqlmodel.sql.sqltypes.AutoString(length=2048),
            nullable=True,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_created_at"), "collection", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_collection_user_id"), "collection", ["user_id"], unique=False
    )
    op.create_table(
        "collection_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("release_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "(book_id IS NOT NULL AND release_id IS NULL) OR (book_id IS NULL AND release_id IS NOT NULL)",
            name="ck_collection_item_exactly_one_target",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collection.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_items_book_id"),
        "collection_items",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_items_collection_id"),
        "collection_items",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_items_release_id"),
        "collection_items",
        ["release_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_collection_items_release_id"), table_name="collection_items")
    op.drop_index(
        op.f("ix_collection_items_collection_id"), table_name="collection_items"
    )
    op.drop_index(op.f("ix_collection_items_book_id"), table_name="collection_items")
    op.drop_table("collection_items")
    op.drop_index(op.f("ix_collection_user_id"), table_name="collection")
    op.drop_index(op.f("ix_collection_created_at"), table_name="collection")
    op.drop_table("collection")
    # ### end Alembic commands ###
