"""add reading session table

Revision ID: 30290a645ea8
Revises: cf8dae74a470
Create Date: 2026-07-05 17:01:18.436864

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30290a645ea8"
down_revision: str | Sequence[str] | None = "cf8dae74a470"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_read", sa.Integer(), nullable=True),
        sa.Column("position_start", sa.Integer(), nullable=True),
        sa.Column("position_end", sa.Integer(), nullable=True),
        sa.Column(
            "position_unit",
            sa.Enum("page", "percent", "location", "timestamp", name="positionunit"),
            nullable=True,
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_sessions_created_at"),
        "reading_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_release_id"),
        "reading_sessions",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_user_id"),
        "reading_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_reading_session_active_user_release",
        "reading_sessions",
        ["user_id", "release_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_reading_session_active_user_release",
        table_name="reading_sessions",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index(op.f("ix_reading_sessions_user_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_release_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_created_at"), table_name="reading_sessions")
    op.drop_table("reading_sessions")
    # ### end Alembic commands ###
