"""add external_source_records table

Revision ID: 3cfc6a4101e7
Revises: b53cf88d0835
Create Date: 2026-07-04 11:49:26.094202

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cfc6a4101e7"
down_revision: Union[str, Sequence[str], None] = "b53cf88d0835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_source_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "ref_kind",
            sa.Enum("search", "isbn", name="externalrefkind"),
            nullable=False,
        ),
        sa.Column("ref", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_source_records_created_at"),
        "external_source_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_source_records_ref"),
        "external_source_records",
        ["ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_source_records_source"),
        "external_source_records",
        ["source"],
        unique=False,
    )
    op.create_index(
        "ix_external_source_records_source_ref_kind_ref",
        "external_source_records",
        ["source", "ref_kind", "ref"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_external_source_records_source_ref_kind_ref",
        table_name="external_source_records",
    )
    op.drop_index(
        op.f("ix_external_source_records_source"), table_name="external_source_records"
    )
    op.drop_index(
        op.f("ix_external_source_records_ref"), table_name="external_source_records"
    )
    op.drop_index(
        op.f("ix_external_source_records_created_at"),
        table_name="external_source_records",
    )
    op.drop_table("external_source_records")
    # ### end Alembic commands ###
