"""add contributor model and roles

Revision ID: 51567b3c0db7
Revises: eda9397ffef8
Create Date: 2026-07-02 13:10:42.630242

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51567b3c0db7"
down_revision: str | Sequence[str] | None = "eda9397ffef8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contributors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "sort_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("death_year", sa.Integer(), nullable=True),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contributors_created_at"), "contributors", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_contributors_full_name"), "contributors", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_contributors_slug"), "contributors", ["slug"], unique=True)
    op.create_index(
        op.f("ix_contributors_sort_name"), "contributors", ["sort_name"], unique=False
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("isbn", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_releases_created_at"), "releases", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_releases_isbn"), "releases", ["isbn"], unique=True)
    op.create_table(
        "book_contributors",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("contributor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "author",
                "co_author",
                "translator",
                "illustrator",
                "editor",
                "narrator",
                "foreword",
                "other",
                name="contributorrole",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("book_id", "contributor_id", "role"),
    )
    op.create_table(
        "release_contributors",
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("contributor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "author",
                "co_author",
                "translator",
                "illustrator",
                "editor",
                "narrator",
                "foreword",
                "other",
                name="contributorrole",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["contributors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("release_id", "contributor_id", "role"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_contributors")
    op.drop_table("book_contributors")
    op.drop_index(op.f("ix_releases_isbn"), table_name="releases")
    op.drop_index(op.f("ix_releases_created_at"), table_name="releases")
    op.drop_table("releases")
    op.drop_index(op.f("ix_contributors_sort_name"), table_name="contributors")
    op.drop_index(op.f("ix_contributors_slug"), table_name="contributors")
    op.drop_index(op.f("ix_contributors_full_name"), table_name="contributors")
    op.drop_index(op.f("ix_contributors_created_at"), table_name="contributors")
    op.drop_table("contributors")
    # ### end Alembic commands ###
