"""add review table

Revision ID: 9d785df4139f
Revises: 3cfc6a4101e7
Create Date: 2026-07-05 14:09:16.395553

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d785df4139f"
down_revision: str | Sequence[str] | None = "3cfc6a4101e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("release_id", sa.Uuid(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("contains_spoilers", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(book_id IS NOT NULL AND release_id IS NULL) OR (book_id IS NULL AND release_id IS NOT NULL)",
            name="ck_review_exactly_one_target",
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 1 AND rating <= 5)",
            name="ck_review_rating_range",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "book_id", name="uq_review_user_book"),
        sa.UniqueConstraint("user_id", "release_id", name="uq_review_user_release"),
    )
    op.create_index(op.f("ix_review_book_id"), "review", ["book_id"], unique=False)
    op.create_index(
        op.f("ix_review_created_at"), "review", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_review_release_id"), "review", ["release_id"], unique=False
    )
    op.create_index(op.f("ix_review_user_id"), "review", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_user_id"), table_name="review")
    op.drop_index(op.f("ix_review_release_id"), table_name="review")
    op.drop_index(op.f("ix_review_created_at"), table_name="review")
    op.drop_index(op.f("ix_review_book_id"), table_name="review")
    op.drop_table("review")
    # ### end Alembic commands ###
