"""add release fields and isbn model

Revision ID: a11a5f31265f
Revises: a7a67f27882c
Create Date: 2026-07-02 19:58:57.700203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a11a5f31265f'
down_revision: Union[str, Sequence[str], None] = 'a7a67f27882c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    releaseformat = sa.Enum('hardcover', 'paperback', 'ebook', 'audiobook', 'other', name='releaseformat')
    isbnkind = sa.Enum('isbn10', 'isbn13', 'asin', 'other', name='isbnkind')
    releaseformat.create(op.get_bind())
    op.create_table('isbns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('code_normalized', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('code_original', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kind', isbnkind, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isbns_code_normalized'), 'isbns', ['code_normalized'], unique=True)
    op.create_index(op.f('ix_isbns_created_at'), 'isbns', ['created_at'], unique=False)
    op.create_index(op.f('ix_isbns_release_id'), 'isbns', ['release_id'], unique=False)
    op.add_column('releases', sa.Column('format', releaseformat, nullable=False))
    op.add_column('releases', sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('releases', sa.Column('published_year', sa.Integer(), nullable=True))
    op.add_column('releases', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False))
    op.add_column('releases', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('releases', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('releases', sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    op.add_column('releases', sa.Column('description_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_releases_isbn'), table_name='releases')
    op.create_index('ix_releases_book_id_format_language', 'releases', ['book_id', 'format', 'language'], unique=False)
    op.drop_column('releases', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('isbn', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index('ix_releases_book_id_format_language', table_name='releases')
    op.create_index(op.f('ix_releases_isbn'), 'releases', ['isbn'], unique=True)
    op.drop_column('releases', 'description_override')
    op.drop_column('releases', 'cover_image_url')
    op.drop_column('releases', 'duration_minutes')
    op.drop_column('releases', 'page_count')
    op.drop_column('releases', 'language')
    op.drop_column('releases', 'published_year')
    op.drop_column('releases', 'publisher')
    op.drop_column('releases', 'format')
    op.drop_index(op.f('ix_isbns_release_id'), table_name='isbns')
    op.drop_index(op.f('ix_isbns_created_at'), table_name='isbns')
    op.drop_index(op.f('ix_isbns_code_normalized'), table_name='isbns')
    op.drop_table('isbns')
    sa.Enum(name='releaseformat').drop(op.get_bind())
    sa.Enum(name='isbnkind').drop(op.get_bind())
    # ### end Alembic commands ###
