"""add book fields and release relationship

Revision ID: a7a67f27882c
Revises: cbd0cbca9f43
Create Date: 2026-07-02 18:26:28.103295

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7a67f27882c"
down_revision: Union[str, Sequence[str], None] = "cbd0cbca9f43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column(
            "original_title",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "book",
        sa.Column(
            "original_language",
            sqlmodel.sql.sqltypes.AutoString(length=35),
            nullable=True,
        ),
    )
    op.add_column(
        "book", sa.Column("first_publication_year", sa.Integer(), nullable=True)
    )
    op.add_column(
        "book",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.execute("UPDATE book SET slug = id::text WHERE slug IS NULL")
    op.alter_column("book", "slug", nullable=False)
    op.create_index(op.f("ix_book_slug"), "book", ["slug"], unique=True)
    op.add_column("releases", sa.Column("book_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_releases_book_id"), "releases", ["book_id"], unique=False)
    op.create_foreign_key(None, "releases", "book", ["book_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "releases", type_="foreignkey")
    op.drop_index(op.f("ix_releases_book_id"), table_name="releases")
    op.drop_column("releases", "book_id")
    op.drop_index(op.f("ix_book_slug"), table_name="book")
    op.drop_column("book", "slug")
    op.drop_column("book", "first_publication_year")
    op.drop_column("book", "original_language")
    op.drop_column("book", "original_title")
    # ### end Alembic commands ###
