"""add password_reset_token table

Revision ID: b1c2d3e4f5g6
Revises: 00562c775707
Create Date: 2026-07-07 17:50:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c2d3e4f5g6"
down_revision: str | Sequence[str] | None = "00562c775707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passwordresettoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("jti", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passwordresettoken_created_at"),
        "passwordresettoken",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passwordresettoken_jti"), "passwordresettoken", ["jti"], unique=True
    )
    op.create_index(
        op.f("ix_passwordresettoken_user_id"),
        "passwordresettoken",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passwordresettoken_user_id"), table_name="passwordresettoken"
    )
    op.drop_index(op.f("ix_passwordresettoken_jti"), table_name="passwordresettoken")
    op.drop_index(
        op.f("ix_passwordresettoken_created_at"), table_name="passwordresettoken"
    )
    op.drop_table("passwordresettoken")
    # ### end Alembic commands ###
