"""add book_status model

Revision ID: b53cf88d0835
Revises: 0bf9abf0e21e
Create Date: 2026-07-03 16:27:07.190818

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b53cf88d0835"
down_revision: Union[str, Sequence[str], None] = "0bf9abf0e21e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_statuses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("release_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "owned",
                "wishlist",
                "pre_order",
                "lent_out",
                "borrowed",
                "gifted_away",
                "sold",
                "lost",
                name="bookstatuskind",
            ),
            nullable=False,
        ),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lent_to_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "lent_to_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("lent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(book_id IS NOT NULL AND release_id IS NULL) OR (book_id IS NULL AND release_id IS NOT NULL)",
            name="ck_book_status_exactly_one_target",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lent_to_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_statuses_book_id"), "book_statuses", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_statuses_created_at"),
        "book_statuses",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_statuses_lent_to_user_id"),
        "book_statuses",
        ["lent_to_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_statuses_release_id"),
        "book_statuses",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_statuses_user_id"), "book_statuses", ["user_id"], unique=False
    )
    op.create_index(
        "ix_book_statuses_user_id_status",
        "book_statuses",
        ["user_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_book_statuses_user_id_status", table_name="book_statuses")
    op.drop_index(op.f("ix_book_statuses_user_id"), table_name="book_statuses")
    op.drop_index(op.f("ix_book_statuses_release_id"), table_name="book_statuses")
    op.drop_index(op.f("ix_book_statuses_lent_to_user_id"), table_name="book_statuses")
    op.drop_index(op.f("ix_book_statuses_created_at"), table_name="book_statuses")
    op.drop_index(op.f("ix_book_statuses_book_id"), table_name="book_statuses")
    op.drop_table("book_statuses")
    # ### end Alembic commands ###
