"""add import_record_table

Revision ID: bba0f93ce4e4
Revises: 00562c775707
Create Date: 2026-07-07 23:06:47.183296

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bba0f93ce4e4"
down_revision: str | Sequence[str] | None = "00562c775707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "failed", name="importrecordstatus"),
            nullable=False,
        ),
        sa.Column(
            "source_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_import_records_created_at", "import_records", ["created_at"], unique=False
    )
    op.create_index(
        "ix_import_records_user_id", "import_records", ["user_id"], unique=False
    )
    op.create_index(
        "ix_import_records_user_id_file_hash",
        "import_records",
        ["user_id", "file_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_import_records_user_id_file_hash", table_name="import_records")
    op.drop_index("ix_import_records_user_id", table_name="import_records")
    op.drop_index("ix_import_records_created_at", table_name="import_records")
    op.drop_table("import_records")
    # ### end Alembic commands ###
