"""add friendship table

Revision ID: cf8dae74a470
Revises: 9d785df4139f
Create Date: 2026-07-05 15:54:53.273230

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf8dae74a470"
down_revision: str | Sequence[str] | None = "9d785df4139f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendship",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("addressee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "accepted", "declined", "blocked", name="friendshipstatus"
            ),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "requester_id != addressee_id", name="ck_friendship_no_self_friend"
        ),
        sa.ForeignKeyConstraint(
            ["addressee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "requester_id", "addressee_id", name="uq_friendship_requester_addressee"
        ),
    )
    op.create_index(
        op.f("ix_friendship_addressee_id"), "friendship", ["addressee_id"], unique=False
    )
    op.create_index(
        op.f("ix_friendship_created_at"), "friendship", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_friendship_requester_id"), "friendship", ["requester_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friendship_requester_id"), table_name="friendship")
    op.drop_index(op.f("ix_friendship_created_at"), table_name="friendship")
    op.drop_index(op.f("ix_friendship_addressee_id"), table_name="friendship")
    op.drop_table("friendship")
    # ### end Alembic commands ###
