"""add chat tables

Revision ID: d27a7afffe10
Revises: 00562c775707
Create Date: 2026-07-08 07:52:08.695931

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d27a7afffe10"
down_revision: str | Sequence[str] | None = "00562c775707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatthread",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_a_id", sa.Uuid(), nullable=False),
        sa.Column("user_b_id", sa.Uuid(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("user_a_id < user_b_id", name="ck_chat_thread_user_order"),
        sa.ForeignKeyConstraint(
            ["user_a_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_b_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_a_id", "user_b_id", name="uq_chat_thread_users"),
    )
    op.create_index(
        op.f("ix_chatthread_created_at"), "chatthread", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_chatthread_user_a_id"), "chatthread", ["user_a_id"], unique=False
    )
    op.create_index(
        op.f("ix_chatthread_user_b_id"), "chatthread", ["user_b_id"], unique=False
    )
    op.create_table(
        "chatmessage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attachment_book_id", sa.Uuid(), nullable=True),
        sa.Column("attachment_collection_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attachment_book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["attachment_collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["chatthread.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chatmessage_attachment_book_id"),
        "chatmessage",
        ["attachment_book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatmessage_attachment_collection_id"),
        "chatmessage",
        ["attachment_collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chatmessage_created_at"), "chatmessage", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_chatmessage_sender_id"), "chatmessage", ["sender_id"], unique=False
    )
    op.create_index(
        op.f("ix_chatmessage_thread_id"), "chatmessage", ["thread_id"], unique=False
    )
    op.drop_index(
        op.f("ix_contributors_full_name_trgm"),
        table_name="contributors",
        postgresql_ops={"full_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_contributors_full_name_trgm"),
        "contributors",
        ["full_name"],
        unique=False,
        postgresql_ops={"full_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_chatmessage_thread_id"), table_name="chatmessage")
    op.drop_index(op.f("ix_chatmessage_sender_id"), table_name="chatmessage")
    op.drop_index(op.f("ix_chatmessage_created_at"), table_name="chatmessage")
    op.drop_index(
        op.f("ix_chatmessage_attachment_collection_id"), table_name="chatmessage"
    )
    op.drop_index(op.f("ix_chatmessage_attachment_book_id"), table_name="chatmessage")
    op.drop_table("chatmessage")
    op.drop_index(op.f("ix_chatthread_user_b_id"), table_name="chatthread")
    op.drop_index(op.f("ix_chatthread_user_a_id"), table_name="chatthread")
    op.drop_index(op.f("ix_chatthread_created_at"), table_name="chatthread")
    op.drop_table("chatthread")
    # ### end Alembic commands ###
